/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetAchievementsResult"];
                        "application/json": components["schemas"]["GetAchievementsResult"];
                        "text/json": components["schemas"]["GetAchievementsResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Achievements/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetStreakResult"];
                        "application/json": components["schemas"]["GetStreakResult"];
                        "text/json": components["schemas"]["GetStreakResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateStreakCommand"];
                    "text/json": components["schemas"]["UpdateStreakCommand"];
                    "application/*+json": components["schemas"]["UpdateStreakCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UpdateStreakResult"];
                        "application/json": components["schemas"]["UpdateStreakResult"];
                        "text/json": components["schemas"]["UpdateStreakResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/AuditLogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Action?: string;
                    EntityType?: string;
                    EntityId?: string;
                    UserId?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetAuditLogsResult"];
                        "application/json": components["schemas"]["GetAuditLogsResult"];
                        "text/json": components["schemas"]["GetAuditLogsResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/BodyMeasurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BodyMeasurementDto"][];
                        "application/json": components["schemas"]["BodyMeasurementDto"][];
                        "text/json": components["schemas"]["BodyMeasurementDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogMeasurementRequest"];
                    "text/json": components["schemas"]["LogMeasurementRequest"];
                    "application/*+json": components["schemas"]["LogMeasurementRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Chat/{relationshipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    relationshipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatConversationDto"];
                        "application/json": components["schemas"]["ChatConversationDto"];
                        "text/json": components["schemas"]["ChatConversationDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Chat/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                    "text/json": components["schemas"]["SendMessageRequest"];
                    "application/*+json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    SearchTerm?: string;
                    Category?: string;
                    MuscleGroup?: string;
                    Equipment?: string;
                    IncludeCustom?: boolean;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetExercisesResult"];
                        "application/json": components["schemas"]["GetExercisesResult"];
                        "text/json": components["schemas"]["GetExercisesResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateExerciseCommand"];
                    "text/json": components["schemas"]["CreateExerciseCommand"];
                    "application/*+json": components["schemas"]["CreateExerciseCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateExerciseResult"];
                        "application/json": components["schemas"]["CreateExerciseResult"];
                        "text/json": components["schemas"]["CreateExerciseResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Foods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FoodDto"];
                        "application/json": components["schemas"]["FoodDto"];
                        "text/json": components["schemas"]["FoodDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateFoodCommand"];
                    "text/json": components["schemas"]["UpdateFoodCommand"];
                    "application/*+json": components["schemas"]["UpdateFoodCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UpdateFoodResult"];
                        "application/json": components["schemas"]["UpdateFoodResult"];
                        "text/json": components["schemas"]["UpdateFoodResult"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeleteFoodResult"];
                        "application/json": components["schemas"]["DeleteFoodResult"];
                        "text/json": components["schemas"]["DeleteFoodResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    SearchTerm?: string;
                    Barcode?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchFoodsResult"];
                        "application/json": components["schemas"]["SearchFoodsResult"];
                        "text/json": components["schemas"]["SearchFoodsResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateFoodCommand"];
                    "text/json": components["schemas"]["CreateFoodCommand"];
                    "application/*+json": components["schemas"]["CreateFoodCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateFoodResult"];
                        "application/json": components["schemas"]["CreateFoodResult"];
                        "text/json": components["schemas"]["CreateFoodResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGoalDto"];
                        "application/json": components["schemas"]["UserGoalDto"];
                        "text/json": components["schemas"]["UserGoalDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserGoalCommand"];
                    "text/json": components["schemas"]["CreateUserGoalCommand"];
                    "application/*+json": components["schemas"]["CreateUserGoalCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateUserGoalResult"];
                        "application/json": components["schemas"]["CreateUserGoalResult"];
                        "text/json": components["schemas"]["CreateUserGoalResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Goals/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GoalProgressHistoryDto"];
                        "application/json": components["schemas"]["GoalProgressHistoryDto"];
                        "text/json": components["schemas"]["GoalProgressHistoryDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RecordGoalProgressCommand"];
                    "text/json": components["schemas"]["RecordGoalProgressCommand"];
                    "application/*+json": components["schemas"]["RecordGoalProgressCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecordGoalProgressResult"];
                        "application/json": components["schemas"]["RecordGoalProgressResult"];
                        "text/json": components["schemas"]["RecordGoalProgressResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HealthReportDto"];
                        "application/json": components["schemas"]["HealthReportDto"];
                        "text/json": components["schemas"]["HealthReportDto"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HealthReportDto"];
                        "application/json": components["schemas"]["HealthReportDto"];
                        "text/json": components["schemas"]["HealthReportDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Households/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HouseholdDto"];
                        "application/json": components["schemas"]["HouseholdDto"];
                        "text/json": components["schemas"]["HouseholdDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateHouseholdRequest"];
                    "text/json": components["schemas"]["CreateHouseholdRequest"];
                    "application/*+json": components["schemas"]["CreateHouseholdRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Households/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddMemberRequest"];
                    "text/json": components["schemas"]["AddMemberRequest"];
                    "application/*+json": components["schemas"]["AddMemberRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/MealPlans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    StartDate?: string;
                    EndDate?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetMealPlansResult"];
                        "application/json": components["schemas"]["GetMealPlansResult"];
                        "text/json": components["schemas"]["GetMealPlansResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateMealPlanCommand"];
                    "text/json": components["schemas"]["CreateMealPlanCommand"];
                    "application/*+json": components["schemas"]["CreateMealPlanCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateMealPlanResult"];
                        "application/json": components["schemas"]["CreateMealPlanResult"];
                        "text/json": components["schemas"]["CreateMealPlanResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/MealPlans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MealPlanDetailDto"];
                        "application/json": components["schemas"]["MealPlanDetailDto"];
                        "text/json": components["schemas"]["MealPlanDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeleteMealPlanResult"];
                        "application/json": components["schemas"]["DeleteMealPlanResult"];
                        "text/json": components["schemas"]["DeleteMealPlanResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/MealPlans/{id}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddRecipeToMealPlanRequest"];
                    "text/json": components["schemas"]["AddRecipeToMealPlanRequest"];
                    "application/*+json": components["schemas"]["AddRecipeToMealPlanRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AddRecipeToMealPlanResult"];
                        "application/json": components["schemas"]["AddRecipeToMealPlanResult"];
                        "text/json": components["schemas"]["AddRecipeToMealPlanResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FoodDiaryResult"];
                        "application/json": components["schemas"]["FoodDiaryResult"];
                        "text/json": components["schemas"]["FoodDiaryResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateFoodDiaryEntryCommand"];
                    "text/json": components["schemas"]["CreateFoodDiaryEntryCommand"];
                    "application/*+json": components["schemas"]["CreateFoodDiaryEntryCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateFoodDiaryEntryResult"];
                        "application/json": components["schemas"]["CreateFoodDiaryEntryResult"];
                        "text/json": components["schemas"]["CreateFoodDiaryEntryResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Nutrition/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogFoodCommand"];
                    "text/json": components["schemas"]["LogFoodCommand"];
                    "application/*+json": components["schemas"]["LogFoodCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LogFoodResult"];
                        "application/json": components["schemas"]["LogFoodResult"];
                        "text/json": components["schemas"]["LogFoodResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Nutrition/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DailyNutritionResult"];
                        "application/json": components["schemas"]["DailyNutritionResult"];
                        "text/json": components["schemas"]["DailyNutritionResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Nutrition/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AiChatRequest"];
                    "text/json": components["schemas"]["AiChatRequest"];
                    "application/*+json": components["schemas"]["AiChatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AiChatResponse"];
                        "application/json": components["schemas"]["AiChatResponse"];
                        "text/json": components["schemas"]["AiChatResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Nutrition/ai/analyze-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FoodAnalysisResult"];
                        "application/json": components["schemas"]["FoodAnalysisResult"];
                        "text/json": components["schemas"]["FoodAnalysisResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    SearchTerm?: string;
                    Tags?: string[];
                    IncludePublic?: boolean;
                    FavoritesOnly?: boolean;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetRecipesResult"];
                        "application/json": components["schemas"]["GetRecipesResult"];
                        "text/json": components["schemas"]["GetRecipesResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateRecipeCommand"];
                    "text/json": components["schemas"]["CreateRecipeCommand"];
                    "application/*+json": components["schemas"]["CreateRecipeCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateRecipeResult"];
                        "application/json": components["schemas"]["CreateRecipeResult"];
                        "text/json": components["schemas"]["CreateRecipeResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecipeDetailDto"];
                        "application/json": components["schemas"]["RecipeDetailDto"];
                        "text/json": components["schemas"]["RecipeDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRecipeCommand"];
                    "text/json": components["schemas"]["UpdateRecipeCommand"];
                    "application/*+json": components["schemas"]["UpdateRecipeCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UpdateRecipeResult"];
                        "application/json": components["schemas"]["UpdateRecipeResult"];
                        "text/json": components["schemas"]["UpdateRecipeResult"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeleteRecipeResult"];
                        "application/json": components["schemas"]["DeleteRecipeResult"];
                        "text/json": components["schemas"]["DeleteRecipeResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Recipes/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ToggleFavoriteRecipeResult"];
                        "application/json": components["schemas"]["ToggleFavoriteRecipeResult"];
                        "text/json": components["schemas"]["ToggleFavoriteRecipeResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ShoppingLists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShoppingListDto"];
                        "application/json": components["schemas"]["ShoppingListDto"];
                        "text/json": components["schemas"]["ShoppingListDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ShoppingLists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetShoppingListsResult"];
                        "application/json": components["schemas"]["GetShoppingListsResult"];
                        "text/json": components["schemas"]["GetShoppingListsResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateShoppingListRequest"];
                    "text/json": components["schemas"]["CreateShoppingListRequest"];
                    "application/*+json": components["schemas"]["CreateShoppingListRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ShoppingLists/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddShoppingListItemRequest"];
                    "text/json": components["schemas"]["AddShoppingListItemRequest"];
                    "application/*+json": components["schemas"]["AddShoppingListItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ShoppingLists/items/{itemId}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ToggleItemRequest"];
                    "text/json": components["schemas"]["ToggleItemRequest"];
                    "application/*+json": components["schemas"]["ToggleItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/Trainers/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SendTrainerRequestRequest"];
                    "text/json": components["schemas"]["SendTrainerRequestRequest"];
                    "application/*+json": components["schemas"]["SendTrainerRequestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Trainers/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RespondRequest"];
                    "text/json": components["schemas"]["RespondRequest"];
                    "application/*+json": components["schemas"]["RespondRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Trainers/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Trainers/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Trainers/clients/{clientId}/nutrition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Users/me/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthDebugDto"];
                        "application/json": components["schemas"]["AuthDebugDto"];
                        "text/json": components["schemas"]["AuthDebugDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogWorkoutCommand"];
                    "text/json": components["schemas"]["LogWorkoutCommand"];
                    "application/*+json": components["schemas"]["LogWorkoutCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LogWorkoutResult"];
                        "application/json": components["schemas"]["LogWorkoutResult"];
                        "text/json": components["schemas"]["LogWorkoutResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AchievementDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
            iconUrl?: string | null;
            /** Format: int32 */
            points?: number;
            category?: string | null;
            isEarned?: boolean;
            /** Format: date-time */
            earnedAt?: string | null;
        };
        AddMemberRequest: {
            email?: string | null;
        };
        AddRecipeToMealPlanRequest: {
            /** Format: uuid */
            recipeId?: string;
            /** Format: date */
            date?: string;
            mealType?: string | null;
            /** Format: double */
            servings?: number;
        };
        AddRecipeToMealPlanResult: {
            /** Format: uuid */
            id?: string;
            success?: boolean;
        };
        AddShoppingListItemRequest: {
            itemName?: string | null;
            /** Format: double */
            amount?: number | null;
            unit?: string | null;
            category?: string | null;
        };
        AiChatRequest: {
            message?: string | null;
        };
        AiChatResponse: {
            response?: string | null;
        };
        AuditLogDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string | null;
            userEmail?: string | null;
            action?: string | null;
            entityType?: string | null;
            entityId?: string | null;
            details?: string | null;
            ipAddress?: string | null;
            /** Format: date-time */
            timestamp?: string;
        };
        AuthDebugDto: {
            isAuthenticated?: boolean;
            /** Format: uuid */
            userId?: string | null;
            email?: string | null;
            claims?: components["schemas"]["ClaimDto"][] | null;
            user?: components["schemas"]["UserDto"];
            authenticationType?: string | null;
            error?: string | null;
        };
        BodyMeasurementDto: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            date?: string;
            /** Format: double */
            weightKg?: number | null;
            /** Format: double */
            bodyFatPercentage?: number | null;
            /** Format: double */
            muscleMassKg?: number | null;
            /** Format: double */
            waistCm?: number | null;
            /** Format: double */
            hipsCm?: number | null;
            /** Format: double */
            chestCm?: number | null;
            /** Format: double */
            armsCm?: number | null;
            /** Format: double */
            thighsCm?: number | null;
            notes?: string | null;
        };
        ChatConversationDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            relationshipId?: string;
            messages?: components["schemas"]["ChatMessageDto"][] | null;
        };
        ChatMessageDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            senderId?: string;
            content?: string | null;
            /** Format: date-time */
            sentAt?: string;
        };
        ClaimDto: {
            type?: string | null;
            value?: string | null;
        };
        CreateExerciseCommand: {
            name: string;
            description?: string | null;
            category: string;
            muscleGroup?: string | null;
            equipment?: string | null;
            videoUrl?: string | null;
            imageUrl?: string | null;
        };
        CreateExerciseResult: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            success?: boolean;
        };
        CreateFoodCommand: {
            name: string;
            /** Format: double */
            caloriesPer100g?: number;
            /** Format: double */
            proteinPer100g?: number;
            /** Format: double */
            carbsPer100g?: number;
            /** Format: double */
            fatPer100g?: number;
            /** Format: double */
            fiberPer100g?: number | null;
            /** Format: double */
            servingSize?: number;
            servingUnit?: string | null;
            isVerified?: boolean;
        };
        CreateFoodDiaryEntryCommand: {
            /** Format: uuid */
            foodId?: string | null;
            /** Format: uuid */
            recipeId?: string | null;
            /** Format: date */
            entryDate?: string | null;
            mealType: string;
            /** Format: double */
            servings?: number;
            /** Format: double */
            calories?: number | null;
            /** Format: double */
            proteinGrams?: number | null;
            /** Format: double */
            carbsGrams?: number | null;
            /** Format: double */
            fatGrams?: number | null;
            name?: string | null;
        };
        CreateFoodDiaryEntryResult: {
            /** Format: uuid */
            id?: string;
            success?: boolean;
            message?: string | null;
        };
        CreateFoodResult: {
            /** Format: uuid */
            id?: string;
            success?: boolean;
            message?: string | null;
        };
        CreateHouseholdRequest: {
            name?: string | null;
        };
        CreateMealPlanCommand: {
            name?: string | null;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: uuid */
            householdId?: string | null;
            recipes?: components["schemas"]["MealPlanRecipeDto"][] | null;
        };
        CreateMealPlanResult: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: int32 */
            recipeCount?: number;
        };
        CreateRecipeCommand: {
            title: string;
            description?: string | null;
            /** Format: int32 */
            servings?: number;
            /** Format: int32 */
            prepTimeMinutes?: number | null;
            /** Format: int32 */
            cookTimeMinutes?: number | null;
            imageUrl?: string | null;
            isPublic?: boolean;
            /** Format: uuid */
            householdId?: string | null;
            ingredients: components["schemas"]["CreateRecipeIngredientDto"][];
            instructions?: string[] | null;
            tags?: string[] | null;
            nutrition?: components["schemas"]["CreateRecipeNutritionDto"];
        };
        CreateRecipeIngredientDto: {
            /** Format: uuid */
            foodId?: string | null;
            ingredientText: string;
            /** Format: double */
            amount?: number | null;
            unit?: string | null;
        };
        CreateRecipeNutritionDto: {
            /** Format: double */
            caloriesPerServing?: number | null;
            /** Format: double */
            proteinGrams?: number | null;
            /** Format: double */
            carbsGrams?: number | null;
            /** Format: double */
            fatGrams?: number | null;
            /** Format: double */
            fiberGrams?: number | null;
        };
        CreateRecipeResult: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
        };
        CreateShoppingListRequest: {
            name?: string | null;
            /** Format: uuid */
            householdId?: string | null;
        };
        CreateUserGoalCommand: {
            goalType?: string | null;
            /** Format: int32 */
            targetCalories?: number | null;
            /** Format: double */
            targetProteinGrams?: number | null;
            /** Format: double */
            targetCarbsGrams?: number | null;
            /** Format: double */
            targetFatGrams?: number | null;
            /** Format: double */
            targetWeight?: number | null;
            weightUnit?: string | null;
            /** Format: date */
            targetDate?: string | null;
        };
        CreateUserGoalResult: {
            /** Format: uuid */
            id?: string;
            success?: boolean;
            message?: string | null;
        };
        DailyNutritionResult: {
            /** Format: date */
            date?: string;
            /** Format: double */
            totalCalories?: number;
            /** Format: double */
            totalProtein?: number;
            /** Format: double */
            totalCarbs?: number;
            /** Format: double */
            totalFat?: number;
            /** Format: double */
            targetCalories?: number | null;
            /** Format: double */
            targetProtein?: number | null;
            /** Format: double */
            targetCarbs?: number | null;
            /** Format: double */
            targetFat?: number | null;
            mealBreakdown?: components["schemas"]["MealSummary"][] | null;
        };
        DailyTotalsDto: {
            /** Format: double */
            calories?: number;
            /** Format: double */
            protein?: number;
            /** Format: double */
            carbs?: number;
            /** Format: double */
            fat?: number;
        };
        DeleteFoodResult: {
            success?: boolean;
            message?: string | null;
        };
        DeleteMealPlanResult: {
            success?: boolean;
            message?: string | null;
        };
        DeleteRecipeResult: {
            success?: boolean;
            message?: string | null;
        };
        ExerciseDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
            category?: string | null;
            muscleGroup?: string | null;
            equipment?: string | null;
            videoUrl?: string | null;
            imageUrl?: string | null;
            isCustom?: boolean;
            isOwner?: boolean;
        };
        ExerciseSetDto: {
            /** Format: int32 */
            reps?: number | null;
            /** Format: double */
            weightKg?: number | null;
            /** Format: int32 */
            durationSeconds?: number | null;
            /** Format: double */
            distanceMeters?: number | null;
        };
        FoodAnalysisResult: {
            foods?: components["schemas"]["RecognizedFood"][] | null;
            /** Format: double */
            totalCalories?: number;
            /** Format: double */
            confidence?: number;
        };
        FoodDiaryEntryDto: {
            /** Format: uuid */
            id?: string;
            mealType?: string | null;
            name?: string | null;
            /** Format: double */
            servings?: number;
            /** Format: double */
            calories?: number | null;
            /** Format: double */
            proteinGrams?: number | null;
            /** Format: double */
            carbsGrams?: number | null;
            /** Format: double */
            fatGrams?: number | null;
            /** Format: date-time */
            loggedAt?: string;
        };
        FoodDiaryResult: {
            /** Format: date */
            date?: string;
            entries?: components["schemas"]["FoodDiaryEntryDto"][] | null;
            totals?: components["schemas"]["DailyTotalsDto"];
        };
        FoodDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            brand?: string | null;
            barcode?: string | null;
            /** Format: double */
            servingSize?: number;
            servingUnit?: string | null;
            /** Format: double */
            caloriesPer100g?: number;
            /** Format: double */
            proteinPer100g?: number;
            /** Format: double */
            carbsPer100g?: number;
            /** Format: double */
            fatPer100g?: number;
            /** Format: double */
            fiberPer100g?: number | null;
            isVerified?: boolean;
        };
        GetAchievementsResult: {
            achievements?: components["schemas"]["AchievementDto"][] | null;
            /** Format: int32 */
            totalPoints?: number;
            /** Format: int32 */
            earnedCount?: number;
            /** Format: int32 */
            totalCount?: number;
        };
        GetAuditLogsResult: {
            logs?: components["schemas"]["AuditLogDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
        };
        GetExercisesResult: {
            exercises?: components["schemas"]["ExerciseDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            categories?: string[] | null;
            muscleGroups?: string[] | null;
            equipmentOptions?: string[] | null;
        };
        GetMealPlansResult: {
            mealPlans?: components["schemas"]["MealPlanDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        GetRecipesResult: {
            recipes?: components["schemas"]["RecipeDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        GetShoppingListsResult: {
            shoppingLists?: components["schemas"]["ShoppingListSummaryDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        GetStreakResult: {
            /** Format: int32 */
            currentStreak?: number;
            /** Format: int32 */
            longestStreak?: number;
            /** Format: date */
            lastActivityDate?: string | null;
            isActiveToday?: boolean;
        };
        GoalProgressEntryDto: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            date?: string;
            /** Format: double */
            actualCalories?: number;
            /** Format: double */
            actualProteinGrams?: number;
            /** Format: double */
            actualCarbsGrams?: number;
            /** Format: double */
            actualFatGrams?: number;
            /** Format: double */
            actualWeight?: number | null;
            notes?: string | null;
        };
        GoalProgressHistoryDto: {
            goal?: components["schemas"]["UserGoalSummaryDto"];
            progressEntries?: components["schemas"]["GoalProgressEntryDto"][] | null;
        };
        HealthCheckEntryDto: {
            name?: string | null;
            status?: string | null;
            description?: string | null;
            /** Format: double */
            duration?: number;
            tags?: string[] | null;
        };
        HealthReportDto: {
            status?: string | null;
            /** Format: double */
            totalDuration?: number;
            system?: components["schemas"]["SystemInfoDto"];
            entries?: components["schemas"]["HealthCheckEntryDto"][] | null;
        };
        HouseholdDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: uuid */
            createdBy?: string | null;
            /** Format: date-time */
            createdAt?: string;
            members?: components["schemas"]["HouseholdMemberDto"][] | null;
        };
        HouseholdMemberDto: {
            /** Format: uuid */
            userId?: string;
            name?: string | null;
            email?: string | null;
            role?: string | null;
            /** Format: date-time */
            joinedAt?: string;
        };
        LogFoodCommand: {
            /** Format: uuid */
            foodId?: string | null;
            /** Format: uuid */
            recipeId?: string | null;
            /** Format: date */
            entryDate?: string;
            mealType?: string | null;
            /** Format: double */
            servings?: number;
        };
        LogFoodResult: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            calories?: number;
            /** Format: double */
            proteinGrams?: number;
            /** Format: double */
            carbsGrams?: number;
            /** Format: double */
            fatGrams?: number;
            message?: string | null;
        };
        LogMeasurementRequest: {
            /** Format: date-time */
            date?: string | null;
            /** Format: double */
            weightKg?: number | null;
            /** Format: double */
            bodyFatPercentage?: number | null;
            /** Format: double */
            muscleMassKg?: number | null;
            /** Format: double */
            waistCm?: number | null;
            /** Format: double */
            hipsCm?: number | null;
            /** Format: double */
            chestCm?: number | null;
            /** Format: double */
            armsCm?: number | null;
            /** Format: double */
            thighsCm?: number | null;
            notes?: string | null;
        };
        LogWorkoutCommand: {
            name?: string | null;
            /** Format: date */
            workoutDate?: string;
            /** Format: int32 */
            durationMinutes?: number | null;
            /** Format: int32 */
            caloriesBurned?: number | null;
            notes?: string | null;
            exercises?: components["schemas"]["WorkoutExerciseDto"][] | null;
        };
        LogWorkoutResult: {
            /** Format: uuid */
            id?: string;
            message?: string | null;
            /** Format: int32 */
            totalExercises?: number;
            /** Format: int32 */
            totalSets?: number;
        };
        MealPlanDetailDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            recipes?: components["schemas"]["MealPlanRecipeDetailDto"][] | null;
            nutritionSummary?: components["schemas"]["MealPlanNutritionSummaryDto"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MealPlanDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: int32 */
            recipeCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MealPlanNutritionSummaryDto: {
            /** Format: double */
            totalCalories?: number;
            /** Format: double */
            totalProteinGrams?: number;
            /** Format: double */
            totalCarbsGrams?: number;
            /** Format: double */
            totalFatGrams?: number;
            /** Format: int32 */
            daysCount?: number;
            /** Format: double */
            avgCaloriesPerDay?: number;
        };
        MealPlanRecipeDetailDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            recipeId?: string;
            recipeTitle?: string | null;
            recipeImageUrl?: string | null;
            /** Format: date */
            date?: string;
            mealType?: string | null;
            /** Format: double */
            servings?: number;
            /** Format: double */
            caloriesPerServing?: number | null;
        };
        MealPlanRecipeDto: {
            /** Format: uuid */
            recipeId: string;
            /** Format: date */
            date?: string;
            mealType: string;
            /** Format: double */
            servings?: number;
        };
        MealSummary: {
            mealType?: string | null;
            /** Format: double */
            calories?: number;
            /** Format: double */
            protein?: number;
            /** Format: double */
            carbs?: number;
            /** Format: double */
            fat?: number;
            /** Format: int32 */
            itemCount?: number;
        };
        RecipeDetailDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            description?: string | null;
            /** Format: int32 */
            servings?: number;
            /** Format: int32 */
            prepTimeMinutes?: number | null;
            /** Format: int32 */
            cookTimeMinutes?: number | null;
            imageUrl?: string | null;
            isPublic?: boolean;
            isOwner?: boolean;
            isFavorited?: boolean;
            nutrition?: components["schemas"]["RecipeNutritionDto"];
            ingredients?: components["schemas"]["RecipeIngredientDto"][] | null;
            instructions?: components["schemas"]["RecipeInstructionDto"][] | null;
            tags?: string[] | null;
            /** Format: date-time */
            createdAt?: string;
        };
        RecipeDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            description?: string | null;
            /** Format: int32 */
            servings?: number;
            /** Format: int32 */
            prepTimeMinutes?: number | null;
            /** Format: int32 */
            cookTimeMinutes?: number | null;
            imageUrl?: string | null;
            isPublic?: boolean;
            isOwner?: boolean;
            nutrition?: components["schemas"]["RecipeNutritionDto"];
            tags?: string[] | null;
            /** Format: date-time */
            createdAt?: string;
        };
        RecipeIngredientDto: {
            /** Format: uuid */
            foodId?: string | null;
            foodName?: string | null;
            /** Format: double */
            amount?: number | null;
            unit?: string | null;
            ingredientText?: string | null;
        };
        RecipeInstructionDto: {
            /** Format: int32 */
            stepNumber?: number;
            instruction?: string | null;
        };
        RecipeNutritionDto: {
            /** Format: double */
            caloriesPerServing?: number | null;
            /** Format: double */
            proteinGrams?: number | null;
            /** Format: double */
            carbsGrams?: number | null;
            /** Format: double */
            fatGrams?: number | null;
        };
        RecognizedFood: {
            name?: string | null;
            /** Format: double */
            portionGrams?: number;
            /** Format: double */
            calories?: number;
            /** Format: double */
            protein?: number;
            /** Format: double */
            carbs?: number;
            /** Format: double */
            fat?: number;
        };
        RecordGoalProgressCommand: {
            /** Format: int32 */
            actualCalories?: number;
            /** Format: double */
            actualProteinGrams?: number;
            /** Format: double */
            actualCarbsGrams?: number;
            /** Format: double */
            actualFatGrams?: number;
            /** Format: double */
            actualWeight?: number | null;
            /** Format: date */
            date?: string | null;
            notes?: string | null;
        };
        RecordGoalProgressResult: {
            success?: boolean;
            message?: string | null;
            /** Format: uuid */
            id?: string | null;
        };
        RespondRequest: {
            /** Format: uuid */
            relationshipId?: string;
            accept?: boolean;
            canViewNutrition?: boolean | null;
            canViewWorkouts?: boolean | null;
            canViewMeasurements?: boolean | null;
            canMessage?: boolean | null;
        };
        SearchFoodsResult: {
            foods?: components["schemas"]["FoodDto"][] | null;
            /** Format: int32 */
            totalCount?: number;
        };
        SendMessageRequest: {
            /** Format: uuid */
            conversationId?: string;
            content?: string | null;
        };
        SendTrainerRequestRequest: {
            /** Format: uuid */
            trainerId?: string;
        };
        ShoppingListDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            householdId?: string | null;
            items?: components["schemas"]["ShoppingListItemDto"][] | null;
        };
        ShoppingListItemDto: {
            /** Format: uuid */
            id?: string;
            itemName?: string | null;
            /** Format: double */
            amount?: number | null;
            unit?: string | null;
            category?: string | null;
            isChecked?: boolean;
        };
        ShoppingListSummaryDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: int32 */
            totalItems?: number;
            /** Format: int32 */
            checkedItems?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SystemInfoDto: {
            environment?: string | null;
            /** Format: int64 */
            memoryUsageBytes?: number;
            /** Format: double */
            uptimeSeconds?: number;
        };
        ToggleFavoriteRecipeResult: {
            isFavorited?: boolean;
            message?: string | null;
        };
        ToggleItemRequest: {
            isChecked?: boolean;
        };
        UpdateFoodCommand: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: double */
            caloriesPer100g?: number;
            /** Format: double */
            proteinPer100g?: number;
            /** Format: double */
            carbsPer100g?: number;
            /** Format: double */
            fatPer100g?: number;
            /** Format: double */
            fiberPer100g?: number | null;
            /** Format: double */
            servingSize?: number;
            servingUnit?: string | null;
            isVerified?: boolean;
        };
        UpdateFoodResult: {
            success?: boolean;
            message?: string | null;
        };
        UpdateRecipeCommand: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            /** Format: int32 */
            servings?: number;
            /** Format: int32 */
            prepTimeMinutes?: number | null;
            /** Format: int32 */
            cookTimeMinutes?: number | null;
            imageUrl?: string | null;
            isPublic?: boolean;
            ingredients: components["schemas"]["CreateRecipeIngredientDto"][];
            instructions?: string[] | null;
            tags?: string[] | null;
            nutrition?: components["schemas"]["CreateRecipeNutritionDto"];
        };
        UpdateRecipeResult: {
            success?: boolean;
            message?: string | null;
        };
        UpdateStreakCommand: {
            streakType?: string | null;
        };
        UpdateStreakResult: {
            /** Format: int32 */
            currentStreak?: number;
            /** Format: int32 */
            longestStreak?: number;
            isNewRecord?: boolean;
        };
        UpdateUserRequest: {
            name?: string | null;
            image?: string | null;
        };
        UserDto: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            name?: string | null;
            image?: string | null;
            /** Format: date-time */
            createdAt?: string;
            currentGoal?: components["schemas"]["UserGoalSummaryDto"];
            /** Format: int32 */
            streakCount?: number;
        };
        UserGoalDto: {
            /** Format: uuid */
            id?: string;
            goalType?: string | null;
            /** Format: double */
            targetCalories?: number | null;
            /** Format: double */
            targetProteinGrams?: number | null;
            /** Format: double */
            targetCarbsGrams?: number | null;
            /** Format: double */
            targetFatGrams?: number | null;
            /** Format: double */
            targetWeight?: number | null;
            weightUnit?: string | null;
            /** Format: date */
            targetDate?: string | null;
            isActive?: boolean;
        };
        UserGoalSummaryDto: {
            /** Format: double */
            targetCalories?: number | null;
            /** Format: double */
            targetProteinGrams?: number | null;
            /** Format: double */
            targetCarbsGrams?: number | null;
            /** Format: double */
            targetFatGrams?: number | null;
        };
        WorkoutExerciseDto: {
            /** Format: uuid */
            exerciseId?: string;
            sets?: components["schemas"]["ExerciseSetDto"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
